spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    ?? PC? ????? Database??? ?? ???.
    url: jdbc:mysql://${MY_SQL_HOST}/${DATABASE_NAME} # Database?? ?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #    mysql? ??? ??? ?? ??? ?? ???.
    username: ${USER_NAME}
    password: ${USER_PASSWORD} # ??? mysql ????

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
#logging:
#  level:
#    me.silvernine: DEBUG

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
openapi:
  base-url: https://finlife.fss.or.kr/finlifeapi/x.json?auth=&topFinGrpNo=020000&pageNo=1
  api-key: 3e02e8a0e0d228bc1c37c4d0cdfd0531
